/**
 * Auto-generated TypeScript types from JSON Schema
 * DO NOT EDIT MANUALLY
 * Generated by tools/generateSchemaTypes.ts
 */

// ============================================
// Common Type Definitions
// ============================================

/**
 * Cost in ability points to activate an ability
 */
export type SURefActivationCost = number | 'X'
/**
 * Ability tree name
 */
export type SURefTree =
  | 'Advanced Engineer'
  | 'Advanced Hacking'
  | 'Advanced Hauler'
  | 'Advanced Scout'
  | 'Advanced Soldier'
  | 'Augmentation'
  | 'Cyborg'
  | 'Electronics'
  | 'Fabricator'
  | 'Forging'
  | 'Generic'
  | 'Gladitorial Combat'
  | 'Hacking'
  | 'Leadership'
  | 'Legendary Cyborg'
  | 'Legendary Engineer'
  | 'Legendary Fabricator'
  | 'Legendary Hacker'
  | 'Legendary Hauler'
  | 'Legendary Ranger'
  | 'Legendary Scout'
  | 'Legendary Smuggler'
  | 'Legendary Soldier'
  | 'Legendary Union Rep'
  | 'Mech-Tech'
  | 'Mechanical Knowledge'
  | 'Ranger'
  | 'Recon'
  | 'Salvaging'
  | 'Sleuth'
  | 'Smuggler'
  | 'Sniper'
  | 'Survivalist'
  | 'Tactical Warfare'
  | 'Trading'
  | 'Union Rep'

// ============================================
// Enum Type Definitions
// ============================================

/**
 * The source book or expansion for this content
 */
export type SURefSource = 'Salvage Union Workshop Manual'
/**
 * Range bands for abilities and weapons
 */
export type SURefRange = 'Close' | 'Medium' | 'Long' | 'Far' | 'Close/Long'
/**
 * Type of action required to use an ability
 */
export type SURefActionType =
  | 'Passive'
  | 'Free'
  | 'Reaction'
  | 'Turn'
  | 'Short'
  | 'Long'
  | 'DownTime'

// ============================================
// Meta Object Type Definitions
// ============================================

/**
 * SURefMetaDamage dealt by an attack or ability
 */
export interface SURefMetaDamage {
  /**
   * Type of damage (Hit Points or Structure Points)
   */
  type: 'HP' | 'SP'
  amount: number | string
}
/**
 * Special traits and properties of items, systems, or abilities
 */
export type SURefMetaTraits = {
  /**
   * Numeric value for the trait
   */
  amount?: number
  /**
   * Type of trait that doesn't require a numeric value
   */
  type: string
}[]
/**
 * Statistics for mechs, chassis, and vehicles
 */
export interface SURefMetaStats {
  /**
   * Structure points (durability)
   */
  structurePts?: number
  /**
   * Energy points (power capacity)
   */
  energyPts?: number
  /**
   * Heat capacity
   */
  heatCap?: number
  /**
   * Number of system slots
   */
  systemSlots?: number
  /**
   * Number of module slots
   */
  moduleSlots?: number
  /**
   * Cargo capacity
   */
  cargoCap?: number
  /**
   * Technology level
   */
  techLevel?: number
  /**
   * Salvage value in scrap
   */
  salvageValue?: number
  /**
   * Additional notes
   */
  notes?: string
}
/**
 * NPC associated with an entity
 */
export interface SURefMetaNpc {
  /**
   * Name of the NPC
   */
  position: string
  /**
   * Description of the NPC
   */
  description: string
  /**
   * Hit points for creatures and personnel
   */
  hitPoints?: number
  choices?: SURefMetaChoices
}
export interface SURefMetaChoice {
  /**
   * Unique identifier for the entry
   */
  id: string
  /**
   * Name of the choice
   */
  name: string
  /**
   * Description of the choice
   */
  description?: string
  /**
   * Schema for the choice
   */
  schema?: string[]
}
/**
 * SURefMetaChoices available to the player when interacting with the NPC
 */
export type SURefMetaChoices = SURefMetaChoice[]
/**
 * An action, ability, or attack that can be performed
 */
export interface SURefMetaAction {
  /**
   * Name of the action
   */
  name: string
  /**
   * The source book or expansion for this content
   */
  source?: 'Salvage Union Workshop Manual'
  /**
   * Description of what the action does
   */
  description?: string
  /**
   * Mechanical effect of the action
   */
  effect?: string
  /**
   * Cost in ability points to activate an ability
   */
  activationCost?: number | 'X'
  /**
   * Range bands for abilities and weapons
   */
  range?: 'Close' | 'Medium' | 'Long' | 'Far' | 'Close/Long'
  /**
   * Type of action required to use an ability
   */
  actionType?:
    | 'Passive'
    | 'Free'
    | 'Reaction'
    | 'Turn'
    | 'Short'
    | 'Long'
    | 'DownTime'
  traits?: SURefMetaTraits
  damage?: SURefMetaDamage
  stats?: SURefMetaStats
  /**
   * List of options or choices for this action
   */
  options?: (
    | string
    | {
        /**
         * Display label for the option
         */
        label: string
        /**
         * Value or effect of the option
         */
        value: string
      }
  )[]
  choices?: SURefMetaChoices
  table?: SURefMetaTable
  /**
   * Page number in the source book
   */
  page?: number
}
/**
 * A system or module that can be installed on a mech
 */
export interface SURefMetaSystem {
  /**
   * Unique identifier for the entry
   */
  id: string
  /**
   * Name of the system or module
   */
  name: string
  /**
   * The source book or expansion for this content
   */
  source?: 'Salvage Union Workshop Manual'
  /**
   * Technology level required
   */
  techLevel?: number
  /**
   * Number of slots required to install
   */
  slotsRequired?: number
  /**
   * Salvage value in scrap
   */
  salvageValue?: number
  /**
   * Whether this is a recommended starting system
   */
  recommended?: boolean
  traits?: SURefMetaTraits
  /**
   * Description of the system or module
   */
  description?: string
  /**
   * Additional notes
   */
  notes?: string
  /**
   * Cost in ability points to activate an ability
   */
  activationCost?: number | 'X'
  /**
   * Range bands for abilities and weapons
   */
  range?: 'Close' | 'Medium' | 'Long' | 'Far' | 'Close/Long'
  damage?: SURefMetaDamage
  table?: SURefMetaTable
  /**
   * Type of action required to use an ability
   */
  actionType?:
    | 'Passive'
    | 'Free'
    | 'Reaction'
    | 'Turn'
    | 'Short'
    | 'Long'
    | 'DownTime'
  /**
   * Actions that can be performed with this system
   */
  actions?: SURefMetaAction[]
  /**
   * Bonus to a specific stat
   */
  statBonus?: {
    /**
     * Name of the stat to bonus
     */
    stat: string
    /**
     * Amount of bonus to apply
     */
    bonus: number
  }
  /**
   * Number of this system included
   */
  count?: number
  /**
   * Page number in the source book
   */
  page: number
}
/**
 * Roll table for random outcomes based on d20 rolls
 */
export type SURefMetaTable =
  | {
      /**
       * Critical failure outcome
       */
      '1': string
      /**
       * Critical success outcome
       */
      '20': string
      type: 'standard'
      /**
       * High success outcome
       */
      '11-19': string
      /**
       * Moderate outcome
       */
      '6-10': string
      /**
       * Low outcome
       */
      '2-5': string
    }
  | {
      /**
       * Critical failure outcome
       */
      '1': string
      type: 'alternate'
      /**
       * Critical success outcome
       */
      '19-20': string
      /**
       * High success outcome
       */
      '11-18': string
      /**
       * Moderate outcome
       */
      '6-10': string
      /**
       * Low outcome
       */
      '2-5': string
    }
  | {
      '1': string
      '2': string
      '3': string
      '4': string
      '5': string
      '6': string
      '7': string
      '8': string
      '9': string
      '10': string
      '11': string
      '12': string
      '13': string
      '14': string
      '15': string
      '16': string
      '17': string
      '18': string
      '19': string
      '20': string
      type: 'flat'
    }
/**
 * Basic entry with name, description, source, and page reference
 */
export interface SURefMetaEntry {
  /**
   * Unique identifier for the entry
   */
  id: string
  /**
   * Name of the entry
   */
  name: string
  /**
   * Description of the entry
   */
  description?: string
  /**
   * The source book or expansion for this content
   */
  source: 'Salvage Union Workshop Manual'
  /**
   * Page number in the source book
   */
  page: number
}

// ============================================
// Main Entity Type Definitions
// ============================================

// Ability
/**
 * Pilot abilities and skills in Salvage Union
 */
export type SURefAbility = {
  /**
   * Unique identifier for the entry
   */
  id: string
  /**
   * Currency used to activate the ability
   */
  activationCurrency?: 'Variable'
  /**
   * Name of the entry
   */
  name: string
  /**
   * Ability tree name
   */
  tree:
    | 'Advanced Engineer'
    | 'Advanced Hacking'
    | 'Advanced Hauler'
    | 'Advanced Scout'
    | 'Advanced Soldier'
    | 'Augmentation'
    | 'Cyborg'
    | 'Electronics'
    | 'Fabricator'
    | 'Forging'
    | 'Generic'
    | 'Gladitorial Combat'
    | 'Hacking'
    | 'Leadership'
    | 'Legendary Cyborg'
    | 'Legendary Engineer'
    | 'Legendary Fabricator'
    | 'Legendary Hacker'
    | 'Legendary Hauler'
    | 'Legendary Ranger'
    | 'Legendary Scout'
    | 'Legendary Smuggler'
    | 'Legendary Soldier'
    | 'Legendary Union Rep'
    | 'Mech-Tech'
    | 'Mechanical Knowledge'
    | 'Ranger'
    | 'Recon'
    | 'Salvaging'
    | 'Sleuth'
    | 'Smuggler'
    | 'Sniper'
    | 'Survivalist'
    | 'Tactical Warfare'
    | 'Trading'
    | 'Union Rep'
  /**
   * The source book or expansion for this content
   */
  source: 'Salvage Union Workshop Manual'
  /**
   * Level in the ability tree (1-3 for normal abilities, 'L' for legendary abilities)
   */
  level?: number | 'L'
  /**
   * Description of the ability
   */
  description?: string
  /**
   * Mechanical effect of the ability
   */
  effect?: string
  /**
   * Cost in ability points to activate an ability
   */
  activationCost?: number | 'X'
  /**
   * Range bands for abilities and weapons
   */
  range?: 'Close' | 'Medium' | 'Long' | 'Far' | 'Close/Long'
  /**
   * Type of action required to use an ability
   */
  actionType?:
    | 'Passive'
    | 'Free'
    | 'Reaction'
    | 'Turn'
    | 'Short'
    | 'Long'
    | 'DownTime'
  /**
   * Type of action required to use an ability
   */
  mechActionType?:
    | 'Passive'
    | 'Free'
    | 'Reaction'
    | 'Turn'
    | 'Short'
    | 'Long'
    | 'DownTime'
  /**
   * Additional notes or requirements for the ability
   */
  notes?: string
  /**
   * Roll table for random outcomes based on d20 rolls
   */
  table?:
    | {
        /**
         * Critical failure outcome
         */
        '1': string
        /**
         * Critical success outcome
         */
        '20': string
        type: 'standard'
        /**
         * High success outcome
         */
        '11-19': string
        /**
         * Moderate outcome
         */
        '6-10': string
        /**
         * Low outcome
         */
        '2-5': string
      }
    | {
        /**
         * Critical failure outcome
         */
        '1': string
        type: 'alternate'
        /**
         * Critical success outcome
         */
        '19-20': string
        /**
         * High success outcome
         */
        '11-18': string
        /**
         * Moderate outcome
         */
        '6-10': string
        /**
         * Low outcome
         */
        '2-5': string
      }
    | {
        '1': string
        '2': string
        '3': string
        '4': string
        '5': string
        '6': string
        '7': string
        '8': string
        '9': string
        '10': string
        '11': string
        '12': string
        '13': string
        '14': string
        '15': string
        '16': string
        '17': string
        '18': string
        '19': string
        '20': string
        type: 'flat'
      }
  traits?: SURefMetaTraits
  /**
   * List of options or choices for this ability
   */
  options?: (
    | string
    | {
        /**
         * Display label for the option
         */
        label: string
        /**
         * Value or effect of the option
         */
        value: string
      }
  )[]
  /**
   * Named sub-abilities with separate mechanics
   */
  actions?: SURefMetaAction[]
  /**
   * Page number in the source book
   */
  page: number
}[]

// AbilityTreeRequirement
/**
 * Requirements for ability trees in Salvage Union
 */
export type SURefAbilityTreeRequirement = {
  /**
   * Unique identifier for the entry
   */
  id: string
  /**
   * Ability tree name
   */
  name:
    | 'Advanced Engineer'
    | 'Advanced Hacking'
    | 'Advanced Hauler'
    | 'Advanced Scout'
    | 'Advanced Soldier'
    | 'Augmentation'
    | 'Cyborg'
    | 'Electronics'
    | 'Fabricator'
    | 'Forging'
    | 'Generic'
    | 'Gladitorial Combat'
    | 'Hacking'
    | 'Leadership'
    | 'Legendary Cyborg'
    | 'Legendary Engineer'
    | 'Legendary Fabricator'
    | 'Legendary Hacker'
    | 'Legendary Hauler'
    | 'Legendary Ranger'
    | 'Legendary Scout'
    | 'Legendary Smuggler'
    | 'Legendary Soldier'
    | 'Legendary Union Rep'
    | 'Mech-Tech'
    | 'Mechanical Knowledge'
    | 'Ranger'
    | 'Recon'
    | 'Salvaging'
    | 'Sleuth'
    | 'Smuggler'
    | 'Sniper'
    | 'Survivalist'
    | 'Tactical Warfare'
    | 'Trading'
    | 'Union Rep'
  /**
   * List of ability tree names required to access this tree
   */
  requirement: (
    | 'Advanced Engineer'
    | 'Advanced Hacking'
    | 'Advanced Hauler'
    | 'Advanced Scout'
    | 'Advanced Soldier'
    | 'Augmentation'
    | 'Cyborg'
    | 'Electronics'
    | 'Fabricator'
    | 'Forging'
    | 'Generic'
    | 'Gladitorial Combat'
    | 'Hacking'
    | 'Leadership'
    | 'Legendary Cyborg'
    | 'Legendary Engineer'
    | 'Legendary Fabricator'
    | 'Legendary Hacker'
    | 'Legendary Hauler'
    | 'Legendary Ranger'
    | 'Legendary Scout'
    | 'Legendary Smuggler'
    | 'Legendary Soldier'
    | 'Legendary Union Rep'
    | 'Mech-Tech'
    | 'Mechanical Knowledge'
    | 'Ranger'
    | 'Recon'
    | 'Salvaging'
    | 'Sleuth'
    | 'Smuggler'
    | 'Sniper'
    | 'Survivalist'
    | 'Tactical Warfare'
    | 'Trading'
    | 'Union Rep'
  )[]
  /**
   * Page number in the source book
   */
  page: number
  /**
   * The source book or expansion for this content
   */
  source: 'Salvage Union Workshop Manual'
}[]

// BioTitan
/**
 * Massive bio-engineered titan creatures in Salvage Union
 */
export type SURefBioTitan = {
  /**
   * Unique identifier for the entry
   */
  id: string
  /**
   * Name of the bio-titan
   */
  name: string
  /**
   * The source book or expansion for this content
   */
  source: 'Salvage Union Workshop Manual'
  /**
   * Description of the bio-titan
   */
  description?: string
  /**
   * Structure points for mechs, vehicles, and titans
   */
  structurePoints: number
  /**
   * Special abilities of this bio-titan
   */
  actions?: SURefMetaAction[]
  /**
   * Page number in the source book
   */
  page: number
}[]

// Chassis
/**
 * Mech chassis definitions in Salvage Union
 */
export type SURefChassis = {
  /**
   * Unique identifier for the entry
   */
  id: string
  /**
   * Name of the chassis
   */
  name: string
  /**
   * The source book or expansion for this content
   */
  source: 'Salvage Union Workshop Manual'
  /**
   * Structure points (durability)
   */
  structurePts?: number
  /**
   * Energy points (power capacity)
   */
  energyPts?: number
  /**
   * Heat capacity
   */
  heatCap?: number
  /**
   * Number of system slots
   */
  systemSlots?: number
  /**
   * Number of module slots
   */
  moduleSlots?: number
  /**
   * Cargo capacity
   */
  cargoCap?: number
  /**
   * Technology level
   */
  techLevel?: number
  /**
   * Salvage value in scrap
   */
  salvageValue?: number
  /**
   * Special abilities built into this chassis
   */
  chassisAbilities?: SURefMetaAction[]
  /**
   * Description of the chassis
   */
  description?: string
  /**
   * Loadout patterns for this chassis
   */
  patterns?: {
    /**
     * Name of the pattern
     */
    name: string
    /**
     * Description of the pattern
     */
    description?: string
    /**
     * Whether this pattern is legal for starting characters
     */
    legalStarting?: boolean
    /**
     * Systems included in this pattern
     */
    systems?: string[]
    /**
     * Modules included in this pattern
     */
    modules?: string[]
    /**
     * Drone loadout for patterns that include drones
     */
    drone?: {
      /**
       * Systems for the drone
       */
      systems?: string[]
      /**
       * Modules for the drone
       */
      modules?: string[]
    }
  }[]
  /**
   * Page number in the source book
   */
  page: number
}[]

// AdvancedClass
/**
 * Advanced character classes in Salvage Union
 */
export type SURefAdvancedClass = {
  /**
   * Unique identifier for the entry
   */
  id: string
  /**
   * Name of the entry
   */
  name: string
  /**
   * The source book or expansion for this content
   */
  source: 'Salvage Union Workshop Manual'
  /**
   * Description of the class
   */
  description?: string
  /**
   * Advanced ability tree for this class
   */
  advancedTree:
    | 'Advanced Engineer'
    | 'Advanced Hacking'
    | 'Advanced Hauler'
    | 'Advanced Scout'
    | 'Advanced Soldier'
    | 'Augmentation'
    | 'Cyborg'
    | 'Electronics'
    | 'Fabricator'
    | 'Forging'
    | 'Generic'
    | 'Gladitorial Combat'
    | 'Hacking'
    | 'Leadership'
    | 'Legendary Cyborg'
    | 'Legendary Engineer'
    | 'Legendary Fabricator'
    | 'Legendary Hacker'
    | 'Legendary Hauler'
    | 'Legendary Ranger'
    | 'Legendary Scout'
    | 'Legendary Smuggler'
    | 'Legendary Soldier'
    | 'Legendary Union Rep'
    | 'Mech-Tech'
    | 'Mechanical Knowledge'
    | 'Ranger'
    | 'Recon'
    | 'Salvaging'
    | 'Sleuth'
    | 'Smuggler'
    | 'Sniper'
    | 'Survivalist'
    | 'Tactical Warfare'
    | 'Trading'
    | 'Union Rep'
  /**
   * Legendary ability tree for this class
   */
  legendaryTree:
    | 'Advanced Engineer'
    | 'Advanced Hacking'
    | 'Advanced Hauler'
    | 'Advanced Scout'
    | 'Advanced Soldier'
    | 'Augmentation'
    | 'Cyborg'
    | 'Electronics'
    | 'Fabricator'
    | 'Forging'
    | 'Generic'
    | 'Gladitorial Combat'
    | 'Hacking'
    | 'Leadership'
    | 'Legendary Cyborg'
    | 'Legendary Engineer'
    | 'Legendary Fabricator'
    | 'Legendary Hacker'
    | 'Legendary Hauler'
    | 'Legendary Ranger'
    | 'Legendary Scout'
    | 'Legendary Smuggler'
    | 'Legendary Soldier'
    | 'Legendary Union Rep'
    | 'Mech-Tech'
    | 'Mechanical Knowledge'
    | 'Ranger'
    | 'Recon'
    | 'Salvaging'
    | 'Sleuth'
    | 'Smuggler'
    | 'Sniper'
    | 'Survivalist'
    | 'Tactical Warfare'
    | 'Trading'
    | 'Union Rep'
  /**
   * Page number in the source book
   */
  page: number
}[]

// CoreClass
/**
 * Core character classes in Salvage Union
 */
export type SURefCoreClass = {
  /**
   * Unique identifier for the entry
   */
  id: string
  /**
   * Indicates if this class can advance into an advanced / hybrid class
   */
  advanceable: boolean
  /**
   * Maximum number of abilities a character can have
   */
  maxAbilities: number
  /**
   * Name of the entry
   */
  name: string
  /**
   * The source book or expansion for this content
   */
  source: 'Salvage Union Workshop Manual'
  /**
   * Description of the class
   */
  description?: string
  /**
   * Core ability trees for this class
   */
  coreTrees?: (
    | 'Advanced Engineer'
    | 'Advanced Hacking'
    | 'Advanced Hauler'
    | 'Advanced Scout'
    | 'Advanced Soldier'
    | 'Augmentation'
    | 'Cyborg'
    | 'Electronics'
    | 'Fabricator'
    | 'Forging'
    | 'Generic'
    | 'Gladitorial Combat'
    | 'Hacking'
    | 'Leadership'
    | 'Legendary Cyborg'
    | 'Legendary Engineer'
    | 'Legendary Fabricator'
    | 'Legendary Hacker'
    | 'Legendary Hauler'
    | 'Legendary Ranger'
    | 'Legendary Scout'
    | 'Legendary Smuggler'
    | 'Legendary Soldier'
    | 'Legendary Union Rep'
    | 'Mech-Tech'
    | 'Mechanical Knowledge'
    | 'Ranger'
    | 'Recon'
    | 'Salvaging'
    | 'Sleuth'
    | 'Smuggler'
    | 'Sniper'
    | 'Survivalist'
    | 'Tactical Warfare'
    | 'Trading'
    | 'Union Rep'
  )[]
  /**
   * Page number in the source book
   */
  page: number
}[]

// HybridClass
/**
 * Hybrid character classes in Salvage Union
 */
export type SURefHybridClass = {
  /**
   * Unique identifier for the entry
   */
  id: string
  /**
   * Name of the entry
   */
  name: string
  /**
   * The source book or expansion for this content
   */
  source: 'Salvage Union Workshop Manual'
  /**
   * Description of the class
   */
  description?: string
  /**
   * Advanced ability tree for this class
   */
  advancedTree:
    | 'Advanced Engineer'
    | 'Advanced Hacking'
    | 'Advanced Hauler'
    | 'Advanced Scout'
    | 'Advanced Soldier'
    | 'Augmentation'
    | 'Cyborg'
    | 'Electronics'
    | 'Fabricator'
    | 'Forging'
    | 'Generic'
    | 'Gladitorial Combat'
    | 'Hacking'
    | 'Leadership'
    | 'Legendary Cyborg'
    | 'Legendary Engineer'
    | 'Legendary Fabricator'
    | 'Legendary Hacker'
    | 'Legendary Hauler'
    | 'Legendary Ranger'
    | 'Legendary Scout'
    | 'Legendary Smuggler'
    | 'Legendary Soldier'
    | 'Legendary Union Rep'
    | 'Mech-Tech'
    | 'Mechanical Knowledge'
    | 'Ranger'
    | 'Recon'
    | 'Salvaging'
    | 'Sleuth'
    | 'Smuggler'
    | 'Sniper'
    | 'Survivalist'
    | 'Tactical Warfare'
    | 'Trading'
    | 'Union Rep'
  /**
   * Legendary ability tree for this class
   */
  legendaryTree:
    | 'Advanced Engineer'
    | 'Advanced Hacking'
    | 'Advanced Hauler'
    | 'Advanced Scout'
    | 'Advanced Soldier'
    | 'Augmentation'
    | 'Cyborg'
    | 'Electronics'
    | 'Fabricator'
    | 'Forging'
    | 'Generic'
    | 'Gladitorial Combat'
    | 'Hacking'
    | 'Leadership'
    | 'Legendary Cyborg'
    | 'Legendary Engineer'
    | 'Legendary Fabricator'
    | 'Legendary Hacker'
    | 'Legendary Hauler'
    | 'Legendary Ranger'
    | 'Legendary Scout'
    | 'Legendary Smuggler'
    | 'Legendary Soldier'
    | 'Legendary Union Rep'
    | 'Mech-Tech'
    | 'Mechanical Knowledge'
    | 'Ranger'
    | 'Recon'
    | 'Salvaging'
    | 'Sleuth'
    | 'Smuggler'
    | 'Sniper'
    | 'Survivalist'
    | 'Tactical Warfare'
    | 'Trading'
    | 'Union Rep'
  /**
   * Page number in the source book
   */
  page: number
}[]

// CrawlerBay
/**
 * Bays and facilities on Union Crawlers in Salvage Union
 */
export type SURefCrawlerBay = {
  /**
   * Unique identifier for the entry
   */
  id: string
  /**
   * Name of the bay (e.g., 'Command Bay', 'Mech Bay')
   */
  name: string
  /**
   * The source book or expansion for this content
   */
  source: 'Salvage Union Workshop Manual'
  /**
   * Full description of the bay's function and capabilities
   */
  description: string
  /**
   * What happens when this bay is damaged
   */
  damagedEffect: string
  npc: SURefMetaNpc
  /**
   * Effects that vary by tech level
   */
  techLevelEffects?: {
    /**
     * Minimum tech level for this effect
     */
    techLevelMin: number
    /**
     * Maximum tech level for this effect
     */
    techLevelMax: number
    /**
     * Description of the effect at this tech level range
     */
    effect: string
  }[]
  choices?: SURefMetaChoices
  /**
   * Roll table for random outcomes based on d20 rolls
   */
  table?:
    | {
        /**
         * Critical failure outcome
         */
        '1': string
        /**
         * Critical success outcome
         */
        '20': string
        type: 'standard'
        /**
         * High success outcome
         */
        '11-19': string
        /**
         * Moderate outcome
         */
        '6-10': string
        /**
         * Low outcome
         */
        '2-5': string
      }
    | {
        /**
         * Critical failure outcome
         */
        '1': string
        type: 'alternate'
        /**
         * Critical success outcome
         */
        '19-20': string
        /**
         * High success outcome
         */
        '11-18': string
        /**
         * Moderate outcome
         */
        '6-10': string
        /**
         * Low outcome
         */
        '2-5': string
      }
    | {
        '1': string
        '2': string
        '3': string
        '4': string
        '5': string
        '6': string
        '7': string
        '8': string
        '9': string
        '10': string
        '11': string
        '12': string
        '13': string
        '14': string
        '15': string
        '16': string
        '17': string
        '18': string
        '19': string
        '20': string
        type: 'flat'
      }
  /**
   * Special abilities or features of this bay
   */
  actions?: SURefMetaAction[]
  /**
   * Additional notes or special rules
   */
  notes?: string
  /**
   * Page number in the source book
   */
  page: number
}[]

// CrawlerTechLevel
/**
 * Tech levels for Union Crawlers in Salvage Union
 */
export type SURefCrawlerTechLevel = {
  /**
   * Unique identifier for the entry
   */
  id: string
  /**
   * Name of the crawler tech level (e.g., 'Hamlet Crawler', 'Village Crawler')
   */
  name: string
  /**
   * Tech level (1-6)
   */
  techLevel: number
  /**
   * Structure points for this tech level
   */
  structurePoints: number
  /**
   * Minimum approximate population
   */
  populationMin: number
  /**
   * Maximum approximate population (0 means unlimited/25,000+)
   */
  populationMax: number
  /**
   * The source book or expansion for this content
   */
  source: 'Salvage Union Workshop Manual'
  /**
   * Page number in the source book
   */
  page: number
}[]

// Crawler
/**
 * Crawler vehicles in Salvage Union
 */
export type SURefCrawler = {
  /**
   * Unique identifier for the entry
   */
  id: string
  /**
   * Name of the crawler
   */
  name: string
  /**
   * The source book or expansion for this content
   */
  source: 'Salvage Union Workshop Manual'
  /**
   * Description of the crawler
   */
  description?: string
  npc?: SURefMetaNpc
  /**
   * Special abilities of this crawler
   */
  actions?: SURefMetaAction[]
  /**
   * Page number in the source book
   */
  page: number
}[]

// Creature
/**
 * Creatures and wildlife in Salvage Union
 */
export type SURefCreature = {
  /**
   * Unique identifier for the entry
   */
  id: string
  /**
   * Name of the creature
   */
  name: string
  /**
   * The source book or expansion for this content
   */
  source: 'Salvage Union Workshop Manual'
  /**
   * Description of the creature
   */
  description?: string
  /**
   * Hit points for creatures and personnel
   */
  hitPoints: number
  /**
   * Special abilities of this creature
   */
  actions?: SURefMetaAction[]
  traits?: SURefMetaTraits
  /**
   * Page number in the source book
   */
  page: number
}[]

// Drone
/**
 * Autonomous drones in Salvage Union
 */
export type SURefDrone = {
  /**
   * Unique identifier for the entry
   */
  id: string
  /**
   * Name of the drone
   */
  name: string
  /**
   * The source book or expansion for this content
   */
  source: 'Salvage Union Workshop Manual'
  /**
   * Description of the drone
   */
  description?: string
  /**
   * Structure points for mechs, vehicles, and titans
   */
  structurePoints: number
  /**
   * Technology level of the item or entity
   */
  techLevel?: number
  /**
   * Salvage value in credits
   */
  salvageValue?: number
  /**
   * Names of systems installed on this drone
   */
  systems?: string[]
  /**
   * Page number in the source book
   */
  page: number
}[]

// Equipment
/**
 * Pilot equipment and gear in Salvage Union
 */
export type SURefEquipment = {
  /**
   * Unique identifier for the entry
   */
  id: string
  /**
   * Name of the equipment
   */
  name: string
  /**
   * The source book or expansion for this content
   */
  source: 'Salvage Union Workshop Manual'
  /**
   * Technology level of the item or entity
   */
  techLevel?: number
  traits?: SURefMetaTraits
  /**
   * Description of the equipment
   */
  description?: string
  /**
   * Additional notes
   */
  notes?: string
  /**
   * Cost in ability points to activate an ability
   */
  activationCost?: number | 'X'
  /**
   * Range bands for abilities and weapons
   */
  range?: 'Close' | 'Medium' | 'Long' | 'Far' | 'Close/Long'
  damage?: SURefMetaDamage
  /**
   * Type of action required to use an ability
   */
  actionType?:
    | 'Passive'
    | 'Free'
    | 'Reaction'
    | 'Turn'
    | 'Short'
    | 'Long'
    | 'DownTime'
  /**
   * Roll table for random outcomes based on d20 rolls
   */
  table?:
    | {
        /**
         * Critical failure outcome
         */
        '1': string
        /**
         * Critical success outcome
         */
        '20': string
        type: 'standard'
        /**
         * High success outcome
         */
        '11-19': string
        /**
         * Moderate outcome
         */
        '6-10': string
        /**
         * Low outcome
         */
        '2-5': string
      }
    | {
        /**
         * Critical failure outcome
         */
        '1': string
        type: 'alternate'
        /**
         * Critical success outcome
         */
        '19-20': string
        /**
         * High success outcome
         */
        '11-18': string
        /**
         * Moderate outcome
         */
        '6-10': string
        /**
         * Low outcome
         */
        '2-5': string
      }
    | {
        '1': string
        '2': string
        '3': string
        '4': string
        '5': string
        '6': string
        '7': string
        '8': string
        '9': string
        '10': string
        '11': string
        '12': string
        '13': string
        '14': string
        '15': string
        '16': string
        '17': string
        '18': string
        '19': string
        '20': string
        type: 'flat'
      }
  /**
   * Actions that can be performed with this equipment
   */
  actions?: SURefMetaAction[]
  /**
   * Page number in the source book
   */
  page: number
}[]

// Keyword
/**
 * Game keywords and terminology in Salvage Union
 */
export type SURefKeyword = SURefMetaEntry[]

// Meld
/**
 * Meld-infected creatures in Salvage Union
 */
export type SURefMeld = {
  [k: string]: unknown
}[]

// Module
/**
 * Mech modules in Salvage Union
 */
export type SURefModule = SURefMetaSystem[]

// Npc
/**
 * Non-player characters and people in Salvage Union
 */
export type SURefNpc = {
  /**
   * Unique identifier for the entry
   */
  id: string
  /**
   * Name of the NPC
   */
  name: string
  /**
   * The source book or expansion for this content
   */
  source: 'Salvage Union Workshop Manual'
  /**
   * Description of the NPC
   */
  description?: string
  /**
   * Hit points for creatures and personnel
   */
  hitPoints: number
  /**
   * Special abilities of this NPC
   */
  actions?: SURefMetaAction[]
  /**
   * Page number in the source book
   */
  page: number
}[]

// RollTable
/**
 * Random tables and roll tables in Salvage Union
 */
export type SURefRollTable = {
  /**
   * Unique identifier for the entry
   */
  id: string
  /**
   * Name of the table
   */
  name: string
  /**
   * Section or category of the table
   */
  section?: string
  /**
   * The source book or expansion for this content
   */
  source: 'Salvage Union Workshop Manual'
  /**
   * Roll table for random outcomes based on d20 rolls
   */
  table?:
    | {
        /**
         * Critical failure outcome
         */
        '1': string
        /**
         * Critical success outcome
         */
        '20': string
        type: 'standard'
        /**
         * High success outcome
         */
        '11-19': string
        /**
         * Moderate outcome
         */
        '6-10': string
        /**
         * Low outcome
         */
        '2-5': string
      }
    | {
        /**
         * Critical failure outcome
         */
        '1': string
        type: 'alternate'
        /**
         * Critical success outcome
         */
        '19-20': string
        /**
         * High success outcome
         */
        '11-18': string
        /**
         * Moderate outcome
         */
        '6-10': string
        /**
         * Low outcome
         */
        '2-5': string
      }
    | {
        '1': string
        '2': string
        '3': string
        '4': string
        '5': string
        '6': string
        '7': string
        '8': string
        '9': string
        '10': string
        '11': string
        '12': string
        '13': string
        '14': string
        '15': string
        '16': string
        '17': string
        '18': string
        '19': string
        '20': string
        type: 'flat'
      }
  /**
   * Page number in the source book
   */
  page: number
}[]

// Squad
/**
 * NPC squads and groups in Salvage Union
 */
export type SURefSquad = {
  [k: string]: unknown
}[]

// System
/**
 * Mech systems in Salvage Union
 */
export type SURefSystem = SURefMetaSystem[]

// Trait
/**
 * SURefMetaTraits and special properties in Salvage Union
 */
export type SURefTrait = SURefMetaEntry[]

// Vehicle
/**
 * Conventional vehicles in Salvage Union
 */
export type SURefVehicle = {
  /**
   * Unique identifier for the entry
   */
  id: string
  /**
   * Name of the vehicle
   */
  name: string
  /**
   * The source book or expansion for this content
   */
  source: 'Salvage Union Workshop Manual'
  /**
   * Description of the vehicle
   */
  description?: string
  /**
   * Structure points for mechs, vehicles, and titans
   */
  structurePoints: number
  /**
   * Technology level of the item or entity
   */
  techLevel?: number
  /**
   * Salvage value in credits
   */
  salvageValue?: number
  /**
   * Names of systems installed on this vehicle
   */
  systems?: string[]
  traits?: SURefMetaTraits
  /**
   * Page number in the source book
   */
  page: number
}[]
