/**
 * Auto-generated TypeScript object and array types
 * DO NOT EDIT MANUALLY
 * Generated by tools/generateObjectTypes.ts
 */

import type {
  SURefActionType,
  SURefClassType,
  SURefDamageType,
  SURefRange,
  SURefSchemaName,
  SURefSource,
  SURefTree,
} from './enums.js'

import type {
  SURefActivationCost,
  SURefAssetUrl,
  SURefHitPoints,
  SURefId,
  SURefName,
  SURefTechLevel,
} from './common.js'

/**
 * Basic entry with name, description, source, and page reference
 */
export interface SURefMetaEntry {
  asset_url?: SURefAssetUrl
  id: SURefId
  /**
   * Whether this entry should be included in search indexes
   */
  indexable?: boolean
  /**
   * Name of the entry
   */
  name: string
  /**
   * Description of the entry
   */
  description?: string
  /**
   * Additional notes about the entry
   */
  notes?: string
  source: SURefSource
  /**
   * Page number in the source book
   */
  page: number
}

/**
 * Damage dealt by an attack or ability
 */
export interface SURefMetaDamage {
  damageType: SURefDamageType
  amount: number | string
}

/**
 * Special traits and properties of items, systems, or abilities
 */
export interface SURefMetaTrait {
  amount?: number | string
  /**
   * Type of trait that doesn't require a numeric value
   */
  type: string
}

/**
 * Grantable entity with a name and description
 */
export interface SURefMetaGrantable {
  schema: SURefSchemaName | 'choice'
  name: SURefName
}

/**
 * Related entry or reference
 */
export interface SURefMetaEffect {
  /**
   * Display label for the effect (empty string if no label)
   */
  label?: string
  /**
   * Name of the related entry or reference
   */
  value: string
}

/**
 * Statistics for mechs, chassis, and vehicles
 */
export interface SURefMetaStats {
  /**
   * Structure points (durability)
   */
  structurePoints?: number
  /**
   * Energy points (power capacity)
   */
  energyPoints?: number
  /**
   * Heat capacity
   */
  heatCapacity?: number
  /**
   * Number of system slots
   */
  systemSlots?: number
  /**
   * Number of module slots
   */
  moduleSlots?: number
  /**
   * Cargo capacity
   */
  cargoCapacity?: number
  techLevel?: SURefTechLevel
  /**
   * Salvage value in scrap
   */
  salvageValue?: number
}

export interface SURefMetaChoice {
  id: SURefId
  /**
   * Name of the choice
   */
  name: string
  /**
   * Description of the choice
   */
  description?: string
  /**
   * Roll table name for the choice
   */
  rollTable?: string
  /**
   * Entities that can be chosen
   */
  schemaEntities?: string[]
  /**
   * Schema for the choice
   */
  schema?: SURefSchemaName[]
  /**
   * Options for the choice
   */
  customSystemOptions?: SURefMetaSystemModule[]
  /**
   * Constraints for the choice
   */
  constraints?: {
    /**
     * Field to apply the constraint to
     */
    field?: string
    /**
     * Minimum number of choices
     */
    min?: number
    /**
     * Maximum number of choices
     */
    max?: number
  }
}

/**
 * NPC associated with an entity
 */
export interface SURefMetaNpc {
  /**
   * Name of the NPC
   */
  position: string
  /**
   * Description of the NPC
   */
  description: string
  hitPoints: SURefHitPoints
  choices?: SURefMetaChoices
}

export interface SURefMetaPatternSystemModule {
  /**
   * Name of the system or module
   */
  name: string
  /**
   * Number of this system or module included
   */
  count?: number
  /**
   * Preselected choices for this system or module, keyed by choice ID
   */
  preselectedChoices?: Record<string, string>
}

/**
 * Mech chassis pattern configuration
 */
export interface SURefMetaPattern {
  /**
   * Name of the pattern
   */
  name: string
  /**
   * Description of the pattern
   */
  description?: string
  /**
   * Whether this pattern is legal for starting characters
   */
  legalStarting?: boolean
  systems: SURefMetaPatternSystemModule[]
  modules: SURefMetaPatternSystemModule[]
  /**
   * Optional drone configuration for this pattern
   */
  drone?: {
    systems: string[]
    modules: string[]
  }
}

/**
 * Effect that scales with tech level
 */
export interface SURefMetaTechLevelEffect {
  /**
   * Minimum tech level for this effect
   */
  techLevelMin: number
  /**
   * Maximum tech level for this effect
   */
  techLevelMax: number
  effects: SURefMetaEffects
}

/**
 * An action, ability, or attack that can be performed
 */
export interface SURefMetaAction {
  id: SURefId
  /**
   * Structure Points (SP) - the health/durability of the entity
   */
  structurePoints?: number
  /**
   * Energy Points (EP) - the energy/power capacity of the entity
   */
  energyPoints?: number
  /**
   * Heat Capacity - how much heat the entity can handle
   */
  heatCapacity?: number
  /**
   * Number of system slots available
   */
  systemSlots?: number
  /**
   * Number of module slots available
   */
  moduleSlots?: number
  /**
   * Cargo capacity
   */
  cargoCapacity?: number
  techLevel?: SURefTechLevel
  /**
   * Salvage value when scrapped
   */
  salvageValue?: number
  /**
   * Name of the action
   */
  name: string
  /**
   * Description of what the action does
   */
  description?: string
  effects?: SURefMetaEffects
  /**
   * Additional notes or flavor text for the action
   */
  notes?: string
  activationCost?: SURefActivationCost
  range?: SURefRange
  actionType?: SURefActionType
  /**
   * Special traits and properties of items, systems, or abilities
   */
  traits?: SURefMetaTrait[]
  damage?: SURefMetaDamage
  /**
   * List of options or choices for this action
   */
  options?: {
    /**
     * Display label for the option (empty string if no label)
     */
    label: string
    /**
     * Description or effect of the option
     */
    value: string
  }[]
  /**
   * Choices available to the player when interacting with the NPC
   */
  choices?: SURefMetaChoice[]
  table?: SURefMetaTable
  /**
   * Sub-actions or nested actions for this ability
   */
  actions?: SURefMetaAction[]
}

/**
 * A system or module that can be installed on a mech
 */
export interface SURefMetaSystemModule extends SURefMetaStats {
  techLevel: SURefTechLevel
  /**
   * Number of slots required to install
   */
  slotsRequired: number
  /**
   * Salvage value in scrap
   */
  salvageValue: number
  /**
   * Whether this is a recommended starting system
   */
  recommended?: boolean
  /**
   * Number of this system included
   */
  count?: number
  action: SURefMetaAction
  actions: SURefMetaActions
}

/**
 * Roll table for random outcomes based on d20 rolls
 */
export type SURefMetaTable =
  | {
      /**
       * Critical failure outcome
       */
      '1': string
      /**
       * Critical success outcome
       */
      '20': string
      type: 'standard'
      /**
       * High success outcome
       */
      '11-19': string
      /**
       * Moderate outcome
       */
      '6-10': string
      /**
       * Low outcome
       */
      '2-5': string
    }
  | {
      /**
       * Critical failure outcome
       */
      '1': string
      type: 'alternate'
      /**
       * Critical success outcome
       */
      '19-20': string
      /**
       * High success outcome
       */
      '11-18': string
      /**
       * Moderate outcome
       */
      '6-10': string
      /**
       * Low outcome
       */
      '2-5': string
    }
  | {
      '1': string
      '2': string
      '3': string
      '4': string
      '5': string
      '6': string
      '7': string
      '8': string
      '9': string
      '10': string
      '11': string
      '12': string
      '13': string
      '14': string
      '15': string
      '16': string
      '17': string
      '18': string
      '19': string
      '20': string
      type: 'flat'
    }

/**
 * Bonus values that increase with tech level
 */
export type SURefMetaBonusPerTechLevel = SURefMetaStats

/**
 * Advanced or hybrid character class
 */
export interface SURefMetaAdvancedClass extends SURefMetaEntry {
  type: SURefClassType
  advancedTree: SURefTree
  legendaryTree: SURefTree
}

/**
 * List of options or choices for an action
 */
export type SURefMetaActionOptions = {
  /**
   * Display label for the option (empty string if no label)
   */
  label: string
  /**
   * Description or effect of the option
   */
  value: string
}[]

/**
 * Actions that can be performed with this entity
 */
export type SURefMetaActions = SURefMetaAction[]

/**
 * Choices available to the player when interacting with the entity
 */
export type SURefMetaChoices = SURefMetaChoice[]

/**
 * Custom system options for choices
 */
export type SURefMetaCustomSystemOptions = SURefMetaSystemModule[]

/**
 * Related entries or references
 */
export type SURefMetaEffects = SURefMetaEffect[]

/**
 * Entities that can be granted
 */
export type SURefMetaGrants = SURefMetaGrantable[]

/**
 * Module names (string references)
 */
export type SURefMetaModules = string[]

/**
 * Mech chassis pattern configurations
 */
export type SURefMetaPatterns = SURefMetaPattern[]

/**
 * Entity names that can be chosen
 */
export type SURefMetaSchemaEntities = string[]

/**
 * Schema names for filtering choices
 */
export type SURefMetaSchemaNames = SURefSchemaName[]

/**
 * System names (string references)
 */
export type SURefMetaSystems = string[]

/**
 * Effects that scale with tech level
 */
export type SURefMetaTechLevelEffects = SURefMetaTechLevelEffect[]

/**
 * Special traits and properties of items, systems, or abilities
 */
export type SURefMetaTraits = SURefMetaTrait[]
