/**
 * Auto-generated TypeScript object and array types
 * DO NOT EDIT MANUALLY
 * Generated by tools/generateObjectTypes.ts
 */

import type {
  SURefActionType,
  SURefClassType,
  SURefDamageType,
  SURefRange,
  SURefSchemaName,
  SURefTree
} from './enums.js'

import type {
  SURefActivationCost,
  SURefHitPoints,
  SURefId,
  SURefName,
  SURefNonNegativeInteger,
  SURefPositiveInteger,
  SURefSalvageValue,
  SURefTechLevel
} from './common.js'

/**
 * Damage dealt by an attack or ability
 */
export interface SURefMetaDamage {
  damageType: SURefDamageType
  amount: (SURefNonNegativeInteger | string)
}

/**
 * Special traits and properties of items, systems, or abilities
 */
export interface SURefMetaTrait {
  amount?: (SURefNonNegativeInteger | string)
  type: string
}

/**
 * Grantable entity with a name and description
 */
export interface SURefMetaGrantable {
  schema: (SURefSchemaName | 'choice')
  name: SURefName
}

/**
 * Related entry or reference
 */
export interface SURefMetaEffect {
  label?: string
  value: string
}

/**
 * Statistics for mechs, chassis, and vehicles
 */
export interface SURefMetaStats {
  structurePoints?: SURefNonNegativeInteger
  energyPoints?: SURefNonNegativeInteger
  heatCapacity?: SURefNonNegativeInteger
  systemSlots?: SURefNonNegativeInteger
  moduleSlots?: SURefNonNegativeInteger
  cargoCapacity?: SURefNonNegativeInteger
  techLevel?: SURefTechLevel
  salvageValue?: SURefSalvageValue
}

export interface SURefMetaChoice {
  id: SURefId
  name: SURefName
  content?: SURefMetaContent
  rollTable?: string
  schemaEntities?: string[]
  schema?: SURefSchemaName[]
  customSystemOptions?: SURefMetaSystemModule[]
  constraints?: {
    field?: string
    min?: SURefNonNegativeInteger
    max?: SURefNonNegativeInteger
  }
}

/**
 * NPC associated with an entity
 */
export interface SURefMetaNpc {
  position: SURefName
  content?: SURefMetaContent
  hitPoints: SURefHitPoints
  choices?: SURefMetaChoices
}

export interface SURefMetaPatternSystemModule {
  name: SURefName
  count?: SURefNonNegativeInteger
  /**
   * Preselected choices for this system or module, keyed by choice ID
   */
  preselectedChoices?: Record<string, SURefName>
}

/**
 * Mech chassis pattern configuration
 */
export interface SURefMetaPattern {
  name: SURefName
  content?: SURefMetaContent
  legalStarting?: boolean
  systems: SURefMetaPatternSystemModule[]
  modules: SURefMetaPatternSystemModule[]
  /**
   * Optional drone configuration
   */
  drone?: {
    systems: string[]
    modules: string[]
  }
}

/**
 * Effect that scales with tech level
 */
export interface SURefMetaTechLevelEffect {
  techLevelMin: SURefPositiveInteger
  techLevelMax: SURefPositiveInteger
  content: SURefMetaContent
}

/**
 * An action, ability, or attack that can be performed
 */
export interface SURefMetaAction {
  id: SURefId
  content?: SURefMetaContent
  structurePoints?: number
  energyPoints?: number
  heatCapacity?: number
  systemSlots?: number
  moduleSlots?: number
  cargoCapacity?: number
  techLevel?: SURefTechLevel
  salvageValue?: number
  name: SURefName
  activationCost?: SURefActivationCost
  range?: SURefRange
  actionType?: SURefActionType
  traits?: SURefMetaTrait[]
  damage?: SURefMetaDamage
  choices?: SURefMetaChoice[]
  table?: SURefMetaTable
}

/**
 * A system or module that can be installed on a mech
 */
export interface SURefMetaSystemModule extends SURefMetaStats {
  techLevel: SURefTechLevel
  slotsRequired: SURefNonNegativeInteger
  salvageValue: SURefSalvageValue
  recommended?: boolean
  count?: SURefNonNegativeInteger
  actions: SURefMetaActions
}

/**
 * Roll table for random outcomes based on d20 rolls
 */
export type SURefMetaTable =
  {
      /**
       * Critical failure outcome
       */
      '1': string
      /**
       * Critical success outcome
       */
      '20': string
      type: 'standard'
      /**
       * High success outcome
       */
      '11-19': string
      /**
       * Moderate outcome
       */
      '6-10': string
      /**
       * Low outcome
       */
      '2-5': string
    }
  | {
      /**
       * Critical failure outcome
       */
      '1': string
      type: 'alternate'
      /**
       * Critical success outcome
       */
      '19-20': string
      /**
       * High success outcome
       */
      '11-18': string
      /**
       * Moderate outcome
       */
      '6-10': string
      /**
       * Low outcome
       */
      '2-5': string
    }
  | {
      '1': string
      '2': string
      '3': string
      '4': string
      '5': string
      '6': string
      '7': string
      '8': string
      '9': string
      '10': string
      '11': string
      '12': string
      '13': string
      '14': string
      '15': string
      '16': string
      '17': string
      '18': string
      '19': string
      '20': string
      type: 'flat'
    }

/**
 * Bonus values that increase with tech level
 */
export type SURefMetaBonusPerTechLevel = SURefMetaStats

/**
 * Advanced or hybrid character class
 */
export interface SURefMetaAdvancedClass extends SURefMetaBaseEntry {
  type: SURefClassType
  advancedTree: SURefTree
  legendaryTree: SURefTree
}

export type SURefMetaActionOptions = {
  label: string
  value: string
}[]

export type SURefMetaActions = SURefMetaAction[]

export type SURefMetaChoices = SURefMetaChoice[]

export type SURefMetaContent = SURefMetaContentBlock[]

export type SURefMetaCustomSystemOptions = SURefMetaSystemModule[]

export type SURefMetaEffects = SURefMetaEffect[]

export type SURefMetaGrants = SURefMetaGrantable[]

export type SURefMetaModules = string[]

export type SURefMetaPatterns = SURefMetaPattern[]

export type SURefMetaSchemaEntities = string[]

export type SURefMetaSchemaNames = SURefSchemaName[]

export type SURefMetaSystems = string[]

export type SURefMetaTechLevelEffects = SURefMetaTechLevelEffect[]

export type SURefMetaTraits = SURefMetaTrait[]
