/**
 * Auto-generated TypeScript schema types
 * DO NOT EDIT MANUALLY
 * Generated by tools/generateSchemaTypes.ts
 */

import type {
  SURefActionType,
  SURefDamageType,
  SURefTree
} from './enums.js'

import type {
  SURefHitPoints,
  SURefPositiveInteger,
  SURefSalvageValue,
  SURefTechLevel
} from './common.js'

import type {
  SURefMetaActions,
  SURefMetaAdvancedClass,
  SURefMetaBaseEntry,
  SURefMetaBonusPerTechLevel,
  SURefMetaChoice,
  SURefMetaChoices,
  SURefMetaGrants,
  SURefMetaNpc,
  SURefMetaPatterns,
  SURefMetaStats,
  SURefMetaSystemModule,
  SURefMetaSystems,
  SURefMetaTable,
  SURefMetaTechLevelEffects,
  SURefMetaTrait
} from './objects.js'

/**
 * Pilot abilities and skills in Salvage Union
 */
export interface SURefAbility extends SURefMetaBaseEntry {
  description?: string
  tree: SURefTree
  level: (number | 'L' | 'G')
  mechActionType?: SURefActionType
  grants?: SURefMetaGrants
  activationCurrency?: 'Variable'
  actions?: SURefMetaActions
}

/**
 * Requirements for ability trees in Salvage Union
 */
export interface SURefAbilityTreeRequirement extends SURefMetaBaseEntry {
  /**
   * List of ability tree names required to access this tree
   */
  requirement: SURefTree[]
}

/**
 * Massive bio-engineered titan creatures in Salvage Union
 */
export interface SURefBioTitan extends SURefMetaBaseEntry {
  structurePoints: SURefPositiveInteger
  actions: SURefMetaActions
  /**
   * Special traits and properties of items, systems, or abilities
   */
  traits?: SURefMetaTrait[]
}

/**
 * Mech chassis definitions in Salvage Union
 */
export interface SURefChassis extends SURefMetaBaseEntry, SURefMetaStats {
  actions: SURefMetaActions
  patterns: SURefMetaPatterns
  npc?: SURefMetaNpc
}

/**
 * Advanced and Hybrid character classes in Salvage Union
 */
export type SURefAdvancedClass = SURefMetaAdvancedClass

/**
 * Core character classes in Salvage Union
 */
export interface SURefCoreClass extends SURefMetaBaseEntry {
  /**
   * Maximum number of abilities this class can have
   */
  maxAbilities: number
  /**
   * Whether this class can advance to hybrid classes
   */
  advanceable: boolean
  /**
   * Core ability trees available to this class
   */
  coreTrees: SURefTree[]
}

/**
 * Bays and facilities on Union Crawlers in Salvage Union
 */
export interface SURefCrawlerBay extends SURefMetaBaseEntry {
  /**
   * Effect when this bay is damaged
   */
  damagedEffect: string
  npc: SURefMetaNpc
  /**
   * Choices available to the player when interacting with the NPC
   */
  choices?: SURefMetaChoice[]
  actions: SURefMetaActions
  techLevelEffects: SURefMetaTechLevelEffects
  table?: SURefMetaTable
}

/**
 * Tech levels for Union Crawlers in Salvage Union
 */
export interface SURefCrawlerTechLevel extends SURefMetaBaseEntry {
  /**
   * Tech level (1-6)
   */
  techLevel: number
  /**
   * Structure points for this tech level
   */
  structurePoints: number
  /**
   * Minimum approximate population
   */
  populationMin: number
  /**
   * Maximum approximate population (0 means unlimited/25,000+)
   */
  populationMax: number
}

/**
 * Crawler vehicles in Salvage Union
 */
export interface SURefCrawler extends SURefMetaBaseEntry {
  npc: SURefMetaNpc
  actions: SURefMetaActions
}

/**
 * Creatures and wildlife in Salvage Union
 */
export interface SURefCreature extends SURefMetaBaseEntry {
  hitPoints: SURefHitPoints
  actions: SURefMetaActions
  /**
   * Special traits and properties of items, systems, or abilities
   */
  traits?: SURefMetaTrait[]
}

/**
 * Distances in Salvage Union are abstracted into the following Range categories. Both Pilots and Mechs use these Range categories for their movement as well as the effective distances for their weapons and other Abilities. The Mediator can factor in any other difference between the speed and distance of Pilots and Mechs based on the narrative and the situation.
 */
export type SURefDistance = SURefMetaBaseEntry

/**
 * Autonomous drones in Salvage Union
 */
export interface SURefDrone extends SURefMetaBaseEntry {
  structurePoints: SURefPositiveInteger
  techLevel: SURefTechLevel
  salvageValue: SURefSalvageValue
  systems: SURefMetaSystems
}

/**
 * Pilot equipment and gear in Salvage Union
 */
export interface SURefEquipment extends SURefMetaBaseEntry, SURefMetaStats {
  bonusPerTechLevel?: SURefMetaBonusPerTechLevel
  choices?: SURefMetaChoices
  techLevel: SURefTechLevel
  actions: SURefMetaActions
}

/**
 * Game keywords and terminology in Salvage Union
 */
export type SURefKeyword = SURefMetaBaseEntry

/**
 * Meld-infected creatures in Salvage Union
 */
export interface SURefMeld extends SURefMetaBaseEntry {
  actions: SURefMetaActions
  /**
   * Special traits and properties of items, systems, or abilities
   */
  traits?: SURefMetaTrait[]
  /**
   * Salvage value of the meld creature
   */
  salvageValue?: number
  /**
   * Hit points of the meld creature
   */
  hitPoints?: number
  /**
   * Structure points of the meld creature
   */
  structurePoints?: number
}

/**
 * Mech modules in Salvage Union
 */
export type SURefModule = SURefMetaSystemModule & SURefMetaBaseEntry

/**
 * Non-player characters and people in Salvage Union
 */
export interface SURefNPC extends SURefMetaBaseEntry {
  hitPoints: SURefHitPoints
  actions: SURefMetaActions
  /**
   * Special traits and properties of items, systems, or abilities
   */
  traits?: SURefMetaTrait[]
}

/**
 * Random tables and roll tables in Salvage Union
 */
export interface SURefRollTable extends SURefMetaBaseEntry {
  /**
   * Section or category of the roll table
   */
  section: string
  table: SURefMetaTable
}

/**
 * NPC squads and groups in Salvage Union
 */
export interface SURefSquad extends SURefMetaBaseEntry {
  hitPoints?: SURefHitPoints
  actions: SURefMetaActions
  /**
   * Special traits and properties of items, systems, or abilities
   */
  traits?: SURefMetaTrait[]
  damageType?: SURefDamageType
}

/**
 * Mech systems in Salvage Union
 */
export type SURefSystem = SURefMetaSystemModule & SURefMetaBaseEntry

/**
 * Traits and special properties in Salvage Union
 */
export type SURefTrait = SURefMetaBaseEntry

/**
 * Conventional vehicles in Salvage Union
 */
export interface SURefVehicle extends SURefMetaBaseEntry {
  structurePoints: SURefPositiveInteger
  techLevel: SURefTechLevel
  salvageValue: SURefSalvageValue
  systems: string[]
  /**
   * Special traits and properties of items, systems, or abilities
   */
  traits?: SURefMetaTrait[]
}
