name: Publish + Release
on:
  workflow_run:
    workflows: [CI]
    types: [completed]
    branches: [main]

env:
  NPM_CONFIG_TOKEN: ${{ secrets.NPM_TOKEN }}

jobs:
  publish:
    name: Publish to NPM
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - run: bun install --frozen-lockfile

      - name: Build packages
        run: bun run moon :build -u

      - name: Publish to NPM
        run: |
          bun run moon :publish -u
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
